### ISSUE TITLE
Merge: Leading whitespace

### ISSUE THREAD

**Issue by mweinelt** [f-breidenstein/go-gitlab-irc#17]
```
[salt] hexa  merge request #16: firewall: politely reject traffic to 25/tcp to prevent mail abuse (https://git.darmstadt.ccc.de/ffda/salt/merge_requests/16)
```

**Comment by fleaz** [comment]
Das template dafür ist 
```
 {{ .User.Name }} {{ .Merge.Action }} merge request 
```
Das doppelte Whitespace kommt daher dass .Merge.Action leer ist. Das ist jetzt auch leider schon zu lange her um sich ausem Gitlab das json rauszuholen :(

Weißt du noch was du mit dem PR gemacht hast um diese Nachricht zu triggern?
